"""drop legacy linkedin_posts table

Revision ID: 091b026f2a98
Revises: 6af48cf60d12
Create Date: 2026-06-27 21:49:34.811898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091b026f2a98'
down_revision: Union[str, None] = '6af48cf60d12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('linkedin_posts')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('company_name', sa.VARCHAR(length=255), nullable=True),
    sa.Column('business_type', sa.VARCHAR(length=100), nullable=True),
    sa.Column('tone', sa.VARCHAR(length=100), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('posted', sa.BOOLEAN(), nullable=True),
    sa.Column('posted_at', sa.DATETIME(), nullable=True),
    sa.Column('scheduled_time', sa.DATETIME(), nullable=True),
    sa.Column('likes_count', sa.INTEGER(), nullable=True),
    sa.Column('comments_count', sa.INTEGER(), nullable=True),
    sa.Column('shares_count', sa.INTEGER(), nullable=True),
    sa.Column('engagement_rate', sa.FLOAT(), nullable=True),
    sa.Column('template_used', sa.VARCHAR(length=100), nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
