"""add user profile fields and style content_goal

Revision ID: 21696dcc14d7
Revises: f0ad1362b64d
Create Date: 2026-06-25 16:50:08.398987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21696dcc14d7'
down_revision: Union[str, None] = 'f0ad1362b64d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_goal', sa.Text(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('headline', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('company', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('industry', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('bio', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('audience_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('age_range', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('age_range')
        batch_op.drop_column('audience_description')
        batch_op.drop_column('bio')
        batch_op.drop_column('industry')
        batch_op.drop_column('company')
        batch_op.drop_column('title')
        batch_op.drop_column('headline')

    with op.batch_alter_table('style_profiles', schema=None) as batch_op:
        batch_op.drop_column('content_goal')

    # ### end Alembic commands ###
