"""baseline schema: users, style_profiles, content_inbox, followed_sources, posts, scheduled_jobs, legacy linkedin_posts

Revision ID: f0ad1362b64d
Revises: 
Create Date: 2026-06-25 16:27:52.735013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0ad1362b64d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linkedin_posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('posted', sa.Boolean(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('scheduled_time', sa.DateTime(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('engagement_rate', sa.Float(), nullable=True),
    sa.Column('template_used', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('linkedin_id', sa.String(length=255), nullable=True),
    sa.Column('linkedin_access_token', sa.Text(), nullable=True),
    sa.Column('linkedin_refresh_token', sa.Text(), nullable=True),
    sa.Column('token_expires_at', sa.DateTime(), nullable=True),
    sa.Column('posting_mode', sa.String(length=20), nullable=True),
    sa.Column('post_frequency', sa.String(length=20), nullable=True),
    sa.Column('preferred_days', sa.JSON(), nullable=True),
    sa.Column('preferred_time', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('notification_email', sa.Boolean(), nullable=True),
    sa.Column('notification_inapp', sa.Boolean(), nullable=True),
    sa.Column('onboarding_complete', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('content_inbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content_type', sa.String(length=20), nullable=False),
    sa.Column('raw_content', sa.Text(), nullable=False),
    sa.Column('parsed_content', sa.Text(), nullable=True),
    sa.Column('context_note', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=15), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_label', sa.String(length=255), nullable=True),
    sa.Column('suggested_by', sa.String(length=500), nullable=True),
    sa.Column('used_in_post_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('followed_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('scheduled_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.Column('next_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('style_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('tone', sa.String(length=100), nullable=True),
    sa.Column('avg_post_length', sa.Integer(), nullable=True),
    sa.Column('emoji_usage', sa.Integer(), nullable=True),
    sa.Column('hashtag_count', sa.Float(), nullable=True),
    sa.Column('top_topics', sa.JSON(), nullable=True),
    sa.Column('avoid_topics', sa.JSON(), nullable=True),
    sa.Column('preferred_length', sa.String(length=10), nullable=True),
    sa.Column('raw_style_summary', sa.Text(), nullable=True),
    sa.Column('sample_posts_analyzed', sa.Integer(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.Column('parent_post_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('inbox_item_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('linkedin_post_id', sa.String(length=255), nullable=True),
    sa.Column('source_topic', sa.Text(), nullable=True),
    sa.Column('generation_prompt', sa.Text(), nullable=True),
    sa.Column('likes_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.Column('shares_count', sa.Integer(), nullable=True),
    sa.Column('notification_sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['inbox_item_id'], ['content_inbox.id'], ),
    sa.ForeignKeyConstraint(['parent_post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('posts')
    op.drop_table('style_profiles')
    op.drop_table('scheduled_jobs')
    op.drop_table('followed_sources')
    op.drop_table('content_inbox')
    op.drop_table('users')
    op.drop_table('linkedin_posts')
    # ### end Alembic commands ###
